---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3-jdk-10
    command:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - name: test
    image: maven:3-jdk-10
    command:
      - mvn test -B

services:
  - name: docker
    image: docker:dind
    command:
      - --max-concurrent-downloads
      - 6
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run