version: '3'
services:
  api:
    build: ./
    container_name: api
    environment:
      - spring.data.mongodb.host=db
#      - logging.level.org.springframework=DEBUG
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    logging:
      driver: none